// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoARSX0hYcQwXvqg3wXXjne6OQbXWa6nM',
    appId: '1:659682018880:web:9e58c2c5bbef7ee20001a5',
    messagingSenderId: '659682018880',
    projectId: 'pichincha-ventas-oficial',
    authDomain: 'pichincha-ventas-oficial.firebaseapp.com',
    storageBucket: 'pichincha-ventas-oficial.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnHe9CHFOsmK_imtkpWHfDMKKH4vpoBk4',
    appId: '1:659682018880:android:abed655b29b04e220001a5',
    messagingSenderId: '659682018880',
    projectId: 'pichincha-ventas-oficial',
    storageBucket: 'pichincha-ventas-oficial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhTkVUNcX03Ynrc5Yd1PA8g3tcSD8N-kQ',
    appId: '1:659682018880:ios:64ce6b2fa4febb820001a5',
    messagingSenderId: '659682018880',
    projectId: 'pichincha-ventas-oficial',
    storageBucket: 'pichincha-ventas-oficial.firebasestorage.app',
    iosBundleId: 'com.example.appbancoPichinchaVentas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhTkVUNcX03Ynrc5Yd1PA8g3tcSD8N-kQ',
    appId: '1:659682018880:ios:64ce6b2fa4febb820001a5',
    messagingSenderId: '659682018880',
    projectId: 'pichincha-ventas-oficial',
    storageBucket: 'pichincha-ventas-oficial.firebasestorage.app',
    iosBundleId: 'com.example.appbancoPichinchaVentas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoARSX0hYcQwXvqg3wXXjne6OQbXWa6nM',
    appId: '1:659682018880:web:22258449a4569b5d0001a5',
    messagingSenderId: '659682018880',
    projectId: 'pichincha-ventas-oficial',
    authDomain: 'pichincha-ventas-oficial.firebaseapp.com',
    storageBucket: 'pichincha-ventas-oficial.firebasestorage.app',
  );
}
